# Generated by Django 4.1.2 on 2022-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("username", models.CharField(max_length=60)),
                ("password", models.CharField(max_length=128)),
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField()),
                ("modified_at", models.DateTimeField()),
            ],
        ),
    ]
