# Generated by Django 4.1.2 on 2022-11-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
    ]
